name: "DB Setup"
description: "Set up the database"

runs:
  using: "composite"
  steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Docker Compose up
      shell: bash
      run: |
        docker compose up -d
        sleep 10
