name: "Setup and Install Dependencies"
description: "Checkout code and install npm dependencies"

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "npm"
        cache-dependency-path: "package-lock.json"

    - name: Copy .env file
      shell: bash
      run: cp .env-sample .env

    - name: Install npm dependencies
      run: npm install
      shell: bash
