import { Logger } from "drizzle-orm"

type OnQueryFn = (query: string, params: unknown[]) => void

const defaultQueryFn: OnQueryFn = (query, params) => {
  // console.warn("Unhandled query log. If this warn is generated by a service, please be sure to use the services injected in the request.")
}

export default class CustomLogger implements Logger {
  onQuery: OnQueryFn

  constructor(options?: {
    onQuery?: OnQueryFn
  }) {
    this.onQuery = options?.onQuery || defaultQueryFn
  }

  logQuery(query: string, params: unknown[]): void {
    this.onQuery(query, params)
  }
}
