name: PR

on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Copy .env
        run: cp .env.example .env
      
      - name: Docker Compose up
        shell: bash
        run: |
          docker compose up --build -d
          sleep 10

      - name: Run tests
        run: docker compose run --rm app npm run test
      
      - name: Run XSS scan
        run: docker compose run --rm app npm run xss:scan
      
      - name: Docker Compose down
        run: docker compose down -v
